USE HealthcareForm
GO

IF OBJECT_ID(N'[Auth].[AuditLog]', N'U') IS NULL
BEGIN
CREATE TABLE Auth.AuditLog
(
	AuditLogID INT NOT NULL PRIMARY KEY IDENTITY (1,1),
	ModifiedTime DATETIME NOT NULL,
	ModifiedBy VARCHAR(250) NOT NULL,
	Operation VARCHAR(250) NOT NULL,
	SchemaName VARCHAR(250) NOT NULL,
	TableName VARCHAR(250) NOT NULL,
	TableID UNIQUEIDENTIFIER NOT NULL,
	LogData VARCHAR(MAX) NOT NULL
)
END
